"use client";
import { useCallback,useEffect,useState } from "react";

type Connection={connectionId:string;userId:string;role:string;connectedAt:string;lastActivityAt:string};
type Room={documentId:string;ownerId:string;connections:Connection[]};

export default function CollaborationAdmin(){
  const [rooms,setRooms]=useState<Room[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState("");
  const refresh=useCallback(async()=>{const response=await fetch("/api/admin/collaboration",{cache:"no-store"});const data=await response.json().catch(()=>({}));if(response.ok){setRooms(data.rooms||[]);setError("");}else setError(data.error||"Collaboration service unavailable");},[]);
  useEffect(()=>{void refresh();const timer=window.setInterval(refresh,15_000);return()=>window.clearInterval(timer);},[refresh]);
  async function act(action:string,payload:Record<string,string>){setBusy(`${action}:${Object.values(payload)[0]}`);const response=await fetch("/api/admin/collaboration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});if(!response.ok)setError("Operation failed");await refresh();setBusy("");}
  return <main className="min-h-screen bg-[#f6f3ed] p-6 text-[#302b27]"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-[#806d91]">Operator tools</p><h1 className="mt-2 text-3xl">Live collaboration</h1></div><button className="rounded-lg border bg-white px-4 py-2" onClick={()=>void refresh()}>Refresh</button></div>{error&&<p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}<div className="mt-6 space-y-4">{rooms.length===0?<p className="rounded-xl border bg-white p-6">No active collaboration rooms.</p>:rooms.map((room)=><section key={room.documentId} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Document {room.documentId}</h2><p className="text-xs text-gray-500">Owner {room.ownerId} · {room.connections.length} connection(s)</p></div><div className="flex gap-2"><button className="rounded border px-3 py-2 text-sm" disabled={Boolean(busy)} onClick={()=>void act("persist",{documentId:room.documentId})}>Persist</button><button className="rounded bg-red-700 px-3 py-2 text-sm text-white" disabled={Boolean(busy)} onClick={()=>void act("drain",{documentId:room.documentId})}>Drain room</button></div></div><div className="mt-4 space-y-2">{room.connections.map((connection)=><div key={connection.connectionId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-gray-50 p-3 text-sm"><div><p>{connection.userId} · {connection.role}</p><p className="text-xs text-gray-500">Connected {new Date(connection.connectedAt).toLocaleString()} · active {new Date(connection.lastActivityAt).toLocaleString()}</p></div><button className="rounded border border-red-300 px-3 py-2 text-red-800" disabled={Boolean(busy)} onClick={()=>void act("revoke-session",{connectionId:connection.connectionId})}>Revoke session</button></div>)}</div></section>)}</div></div></main>;
}
