"use client";

import { useCallback, useEffect, useState } from "react";
import type { EditorHandle, EditorSelection } from "./editor-types";

type Comment={id:string;content:string;anchorType:string;anchorText:string|null;isResolved:boolean;createdAt:string;user:{id:string;name:string;avatar?:string|null};replies:Array<Comment>};

export function CommentsDrawer({ documentId, open, onClose, editorRef, selectionRef, canResolve, allowComments, currentUserId, canModerate, documentText }: { documentId?:string; open:boolean; onClose:()=>void; editorRef:React.RefObject<EditorHandle|null>; selectionRef:React.RefObject<EditorSelection|null>; canResolve:boolean; allowComments:boolean; currentUserId:string; canModerate:boolean; documentText:string }) {
  const [filter,setFilter]=useState("open");
  const [comments,setComments]=useState<Comment[]>([]);
  const [text,setText]=useState("");
  const [replyFor,setReplyFor]=useState<string|null>(null);
  const [editingId,setEditingId]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{if(!documentId)return;const response=await fetch(`/api/documents/${documentId}/comments?filter=${filter}`,{cache:"no-store"});if(response.ok)setComments(await response.json());},[documentId,filter]);
  useEffect(()=>{if(!open)return;void refresh();const onFocus=()=>void refresh();window.addEventListener("focus",onFocus);const timer=window.setInterval(()=>void refresh(),10_000);return()=>{window.removeEventListener("focus",onFocus);window.clearInterval(timer);};},[open,refresh]);
  useEffect(()=>{if(!open)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();};window.addEventListener("keydown",onKeyDown);return()=>window.removeEventListener("keydown",onKeyDown);},[open,onClose]);
  async function addComment(){const content=text.trim();if(!content||!documentId||!allowComments)return;setBusy(true);const selection=selectionRef.current;const inline=Boolean(selection&&selection.to>selection.from&&selection.text);const response=await fetch(`/api/documents/${documentId}/comments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,anchorType:inline?"inline":"general",anchorText:inline?selection?.text:null})});if(response.ok){const comment=await response.json();if(inline&&selection)editorRef.current?.addCommentMark(comment.id,selection.from,selection.to);setText("");selectionRef.current=null;await refresh();}setBusy(false);}
  async function reply(commentId:string){const content=text.trim();if(!content||!documentId)return;setBusy(true);const response=await fetch(`/api/documents/${documentId}/comments/${commentId}/replies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})});if(response.ok){setText("");setReplyFor(null);await refresh();}setBusy(false);}
  async function mutate(id:string,body:Record<string,unknown>){const response=await fetch(`/api/documents/${documentId}/comments/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(response.ok){setEditingId(null);setText("");await refresh();}}
  async function remove(id:string){if(!window.confirm("Remove this comment?"))return;const response=await fetch(`/api/documents/${documentId}/comments/${id}`,{method:"DELETE"});if(response.ok)await refresh();}
  return <><button className={`mobile-sheet-backdrop ${open?"is-open":""}`} aria-label="Close comments" tabIndex={open?0:-1} onClick={onClose}/><aside className={`comments-drawer ${open?"is-open":""}`} aria-hidden={!open}>
    <div className="comments-drawer__header"><div><strong>Comments</strong><span>Collaborate in context</span></div><button onClick={onClose} aria-label="Close comments">×</button></div>
    <div className="comments-tabs"><button className={filter==="open"?"active":""} onClick={()=>setFilter("open")}>Open</button><button className={filter==="resolved"?"active":""} onClick={()=>setFilter("resolved")}>Resolved</button><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All</button></div>
    {allowComments&&<div className="comment-composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={editingId?"Edit comment…":selectionRef.current?.text?"Comment on this selection…":replyFor?"Reply…":"Add a comment…"}/><button disabled={busy||!text.trim()} onClick={()=>editingId?void mutate(editingId,{content:text}):replyFor?void reply(replyFor):void addComment()}>{editingId?"Save":replyFor?"Reply":"Comment"}</button></div>}
    <div className="comments-drawer__body">{comments.length===0?<p className="history-empty">No {filter} comments.</p>:comments.map(comment=>{const detached=comment.anchorType==="inline"&&Boolean(comment.anchorText)&&!documentText.includes(comment.anchorText||"");return <article className={`comment-thread ${comment.isResolved?"resolved":""}`} key={comment.id}><header><strong>{comment.user.name}</strong><small>{new Date(comment.createdAt).toLocaleString()}</small></header>{detached?<blockquote>Original selection removed</blockquote>:comment.anchorText&&<blockquote>{comment.anchorText}</blockquote>}<p>{comment.content}</p><div className="comment-actions"><button onClick={()=>{setReplyFor(comment.id);setEditingId(null);setText("")}}>Reply</button>{!comment.isResolved&&canResolve&&<button onClick={()=>void mutate(comment.id,{resolved:true})}>Resolve</button>}{comment.isResolved&&canResolve&&<button onClick={()=>void mutate(comment.id,{resolved:false})}>Reopen</button>}{(comment.user.id===currentUserId||canModerate)&&<><button onClick={()=>{setEditingId(comment.id);setReplyFor(null);setText(comment.content)}}>Edit</button><button onClick={()=>void remove(comment.id)}>Remove</button></>}</div>{comment.replies.map(reply=><div className="comment-reply" key={reply.id}><strong>{reply.user.name}</strong><p>{reply.content}</p></div>)}</article>})}</div>
  </aside></>;
}
