"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { useRouter } from "next/navigation";
import { useMemo, useRef, useState, useTransition } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRightIcon, CheckCircleIcon, CopyIcon, DotsThreeIcon, FilePlusIcon, GearSixIcon, GlobeHemisphereWestIcon, MagnifyingGlassIcon, NotePencilIcon, SignOutIcon, SparkleIcon, TrashIcon, UsersThreeIcon } from "@phosphor-icons/react";
import { toast } from "sonner";
import { DocumentsFolderIcon, OmnidocLogo } from "@/components/omnidoc-logo";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { createClient } from "@/lib/supabase/client";
import { MobileBottomNav } from "@/components/mobile-bottom-nav";

const SettingsModal = dynamic(() => import("@/components/setting-modal").then((module) => module.SettingsModal), { ssr: false });
type Person = { id: string; name: string; avatar?: string | null };
type Publication = { id: string; slug: string; isActive: boolean; publishedAt: string; updatedAt: string };
type DashboardDoc = { id: string; title: string; status: "WORKING_DRAFT" | "COMPLETE"; previewText: string; previewImageUrl: string | null; wordCount: number; updatedAt: string; lastEditedAt: string; owned: boolean; publication: Publication | null; collaborators: { role: string; user: Person }[] };
type DashboardUser = { id: string; name: string; email: string; avatar: string };
type Filter = "all" | "draft" | "complete" | "published" | "shared";
function initials(name: string) { return name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function publicationPath(doc: DashboardDoc) { return doc.publication ? `/p/${doc.publication.id}/${doc.publication.slug}` : ""; }

export default function DashboardClient({ user, documents: initialDocuments, greeting }: { user: DashboardUser; documents: DashboardDoc[]; greeting: string }) {
  const router = useRouter(); const reducedMotion = useReducedMotion();
  const [documents, setDocuments] = useState(initialDocuments); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [error, setError] = useState<string | null>(null); const [settingsOpen, setSettingsOpen] = useState(false); const [deleteTarget, setDeleteTarget] = useState<DashboardDoc | null>(null); const [brokenImages, setBrokenImages] = useState<Set<string>>(new Set()); const [creating, startCreating] = useTransition();
  const deleteInFlightRef = useRef<string | null>(null);
  const counts = useMemo(() => ({ all: documents.length, draft: documents.filter((doc) => doc.status === "WORKING_DRAFT").length, complete: documents.filter((doc) => doc.status === "COMPLETE").length, published: documents.filter((doc) => doc.publication?.isActive).length, shared: documents.filter((doc) => !doc.owned).length }), [documents]);
  const filtered = useMemo(() => documents.filter((doc) => { const matchesQuery = `${doc.title} ${doc.previewText}`.toLowerCase().includes(query.trim().toLowerCase()); const matchesFilter = filter === "all" || (filter === "draft" && doc.status === "WORKING_DRAFT") || (filter === "complete" && doc.status === "COMPLETE") || (filter === "published" && doc.publication?.isActive) || (filter === "shared" && !doc.owned); return matchesQuery && matchesFilter; }), [documents, filter, query]);
  function createDocument() { startCreating(() => router.push("/document")); }
  async function deleteDocument() { if (!deleteTarget || deleteInFlightRef.current) return; const target = deleteTarget; deleteInFlightRef.current = target.id; setDeleteTarget(null); const previous = documents; setDocuments((items) => items.filter((item) => item.id !== target.id)); try { const response = await fetch(`/api/documents/${target.id}`, { method: "DELETE" }); if (!response.ok) { setDocuments(previous); setError("That document could not be deleted."); toast.error("Document could not be deleted"); } else toast.success("Document deleted"); } catch { setDocuments(previous); setError("That document could not be deleted."); toast.error("Document could not be deleted"); } finally { deleteInFlightRef.current = null; } }
  async function copyPublicLink(doc: DashboardDoc) { const path = publicationPath(doc); if (!path) return; try { await navigator.clipboard.writeText(`${window.location.origin}${path}`); toast.success("Public link copied"); } catch { setError("The public link could not be copied."); } }
  async function signOut() { router.replace("/signin"); const { error: logoutError } = await createClient().auth.signOut({ scope: "local" }); if (logoutError) toast.error("Signed out locally, but session cleanup failed."); router.refresh(); }
  const filters: Array<{ id: Filter; label: string }> = [{ id: "all", label: "All" }, { id: "draft", label: "Working drafts" }, { id: "complete", label: "Complete" }, { id: "published", label: "Published" }, { id: "shared", label: "Shared" }];
  return <main className="min-h-screen bg-[#f5f3ee] text-[#29251f] md:grid md:grid-cols-[88px_minmax(0,1fr)]">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[88px] flex-col items-center justify-between border-r border-[#ded8cd] bg-[#fffdf8] py-7 md:flex"><Link href="/" aria-label="Omnidoc" className="grid place-items-center"><OmnidocLogo priority className="h-9 w-9" /></Link><nav className="grid gap-3"><button className="grid h-11 w-11 place-items-center rounded-xl bg-[#eee8f6] text-[#40355f]" aria-label="Documents folder"><DocumentsFolderIcon /></button><button onClick={() => setSettingsOpen(true)} className="grid h-11 w-11 place-items-center rounded-xl text-[#817a70] hover:bg-[#eeeae3]" aria-label="Settings"><GearSixIcon /></button></nav><button onClick={signOut} className="grid h-11 w-11 place-items-center rounded-xl text-[#817a70] hover:bg-[#eeeae3]" aria-label="Sign out"><SignOutIcon /></button></aside>
    <MobileBottomNav className="dash-mobile-nav" ariaLabel="Dashboard navigation" items={[{id:"documents",label:"Docs",icon:<DocumentsFolderIcon/>,onClick:()=>router.push("/dashboard"),active:true},{id:"new",label:"New",icon:<FilePlusIcon/>,onClick:createDocument},{id:"settings",label:"Settings",icon:<GearSixIcon/>,onClick:()=>setSettingsOpen(true)},{id:"signout",label:"Sign out",icon:<SignOutIcon/>,onClick:()=>void signOut()}]} />
    <div className="min-w-0 px-4 pb-28 sm:px-8 md:col-start-2 md:px-10 lg:px-20">
      <header className="flex h-[65px] items-center justify-between border-b border-transparent md:h-[78px]"><Link href="/" className="flex items-center gap-2 text-[20px] text-[#302b27] no-underline"><OmnidocLogo className="h-7 w-7" />Omnidoc</Link><div className="flex min-w-0 items-center gap-3 text-xs text-[#615950]"><span className="max-w-[42vw] truncate sm:max-w-none">{user.name}</span><div className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-full bg-[#2d2924] text-[11px] text-white">{user.avatar?.startsWith("http") ? <img src={user.avatar} alt="" className="h-full w-full object-cover" /> : initials(user.name)}</div></div></header>
      <section className="flex flex-col justify-between gap-7 border-b border-[#dcd7cc] py-10 sm:py-16 lg:flex-row lg:items-end"><div><span className="text-[10px] uppercase tracking-[.15em] text-[#74618e]">Documents</span><h1 className="mt-4 font-[var(--font-instrument)] text-[clamp(42px,6vw,78px)] font-normal leading-[.9] tracking-[-.045em]">Good {greeting},<br /><i className="font-normal text-[#66547e]">{user.name.split(" ")[0]}.</i></h1><p className="mt-5 max-w-[520px] text-[13px] leading-7 text-[#6f685f]">Everything in progress, ready to share, and published lives in one quiet place.</p></div><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#40355f] px-4 text-[13px] text-white shadow-[0_13px_26px_rgba(64,53,95,.18)] hover:bg-[#342a52] disabled:opacity-60 lg:w-auto" onClick={createDocument} disabled={creating}><FilePlusIcon />{creating ? "Opening…" : "New document"}<ArrowRightIcon /></button></section>
      <section className="pt-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-baseline gap-3"><h2 className="font-[var(--font-instrument)] text-[29px] font-normal sm:text-[33px]">Your library</h2><span className="text-[11px] text-[#918a80]">{documents.length} {documents.length === 1 ? "document" : "documents"}</span></div></div><label className="flex h-11 w-full items-center gap-2 rounded-[10px] border border-[#d9d3c8] bg-[#fbfaf6] px-3 text-[#8b847a] focus-within:border-[#88759d] focus-within:ring-4 focus-within:ring-[#5a4870]/10 sm:w-[270px]"><MagnifyingGlassIcon /><input className="min-w-0 w-full border-0 bg-transparent text-xs outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles and pages" aria-label="Search documents" /></label></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Filter documents">{filters.map((item) => <button className="flex min-h-10 shrink-0 items-center gap-2 rounded-full border border-transparent px-3 text-[11px] text-[#777066] hover:bg-[#eeeae3] aria-selected:border-[#d7d0df] aria-selected:bg-[#ebe7f0] aria-selected:text-[#443953]" key={item.id} role="tab" aria-selected={filter === item.id} onClick={() => setFilter(item.id)}>{item.label}<span className="grid min-w-[18px] place-items-center rounded-full bg-white/70 px-1.5 py-0.5 text-[9px]">{counts[item.id]}</span></button>)}</div>
        {error && <div role="alert" className="mt-4 flex items-center justify-between gap-3 rounded-[10px] border border-[#f2c8c2] bg-[#fff0ec] px-3.5 py-3 text-xs text-[#95392f]">{error}<button className="underline" onClick={() => setError(null)}>Dismiss</button></div>}
        <AnimatePresence mode="popLayout">{filtered.length ? <motion.div layout className="mt-5 grid min-w-0 grid-cols-1 gap-4 lg:grid-cols-3 md:grid-cols-2">{filtered.map((doc, index) => <motion.article layout key={doc.id} initial={reducedMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .2, delay: reducedMotion ? 0 : Math.min(index * .025, .12) }} className="min-w-0 overflow-hidden rounded-[15px] border border-[#ddd8ce] bg-[#fbfaf6] transition hover:-translate-y-1 hover:border-[#cfc7ba] hover:shadow-[0_20px_46px_rgba(54,45,31,.08)]">
          <Link href={`/document/${doc.id}`} prefetch className="block min-w-0 text-inherit no-underline"><div className={`relative mx-3 mt-3 h-[178px] overflow-hidden rounded-[9px] border border-[#e4dfd5] bg-[#fffefa] ${doc.previewImageUrl && !brokenImages.has(doc.id) ? "grid grid-cols-[44%_56%]" : ""}`}>{doc.previewImageUrl && !brokenImages.has(doc.id) && <img src={doc.previewImageUrl} alt="" className="h-full w-full object-cover" onError={() => setBrokenImages((items) => new Set(items).add(doc.id))} />}<div className="min-w-0 p-5"><span className={`inline-flex items-center gap-1 text-[9px] uppercase tracking-[.08em] ${doc.status === "COMPLETE" ? "text-[#4f7964]" : "text-[#8b6e78]"}`}>{doc.status === "COMPLETE" ? <CheckCircleIcon /> : <NotePencilIcon />}{doc.status === "COMPLETE" ? "Complete" : "Working draft"}</span><p className="mt-5 line-clamp-5 font-[var(--font-instrument)] text-[15px] leading-[1.42] text-[#625d56]">{doc.previewText || "A blank page, ready for the first thought."}</p></div></div><div className="flex min-w-0 items-start justify-between gap-3 px-4 pb-3 pt-4"><div className="min-w-0"><h3 className="truncate text-sm font-medium">{doc.title || "Untitled document"}</h3><p className="mt-1 truncate text-[10px] text-[#918a80]">{doc.owned ? "Owned by you" : "Shared with you"} · {formatDate(doc.lastEditedAt)}</p></div><ArrowRightIcon className="shrink-0 text-[#79678d]" /></div></Link>
          <div className="flex min-h-12 flex-wrap items-center gap-2 px-4 pb-3"><div className="flex shrink-0">{doc.collaborators.slice(0, 3).map(({ user: person }) => <span className="-ml-1 grid h-6 w-6 place-items-center rounded-full border-2 border-[#fbfaf6] bg-[#5c5368] text-[8px] text-white first:ml-0" key={person.id} title={person.name}>{initials(person.name)}</span>)}{!doc.collaborators.length && <span className="grid h-6 w-6 place-items-center rounded-full bg-[#e8e3da] text-[#777069]"><UsersThreeIcon /></span>}</div><span className="text-[9px] text-[#9a9389]">{doc.wordCount.toLocaleString("en-US")} words</span>{doc.publication?.isActive && <Link href={publicationPath(doc)} className="ml-auto flex items-center gap-1 text-[9px] text-[#4f7964]" title="View published page"><GlobeHemisphereWestIcon />Live</Link>}<DropdownMenu><DropdownMenuTrigger asChild><button className="ml-auto grid h-9 w-9 place-items-center rounded-lg text-[#918a80] hover:bg-[#eeeae3]" aria-label={`Actions for ${doc.title}`}><DotsThreeIcon weight="bold" /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => router.push(`/document/${doc.id}`)}>Open document</DropdownMenuItem>{doc.publication?.isActive && <><DropdownMenuItem onClick={() => window.open(publicationPath(doc), "_blank", "noopener,noreferrer")}>View published page</DropdownMenuItem><DropdownMenuItem onClick={() => void copyPublicLink(doc)}><CopyIcon />Copy public link</DropdownMenuItem></>}{doc.owned && <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setDeleteTarget(doc)}><TrashIcon />Delete</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>
        </motion.article>)}</motion.div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-5 flex flex-col items-center justify-center rounded-[15px] border border-dashed border-[#cfc8bc] bg-white/40 px-5 py-20 text-center"><SparkleIcon size={30} weight="duotone" className="text-[#76648d]" /><h3 className="mt-4 font-[var(--font-instrument)] text-[29px] font-normal">{query ? "Nothing matches that search" : filter === "all" ? "A clean page is waiting" : `No ${filters.find((item) => item.id === filter)?.label.toLowerCase()} yet`}</h3><p className="text-xs text-[#7b756c]">{query ? "Try another title or phrase." : "Start a document and it will appear here as soon as the first thought lands."}</p>{!query && filter === "all" && <button className="mt-5 rounded-[9px] bg-[#40355f] px-3.5 py-2.5 text-xs text-white" onClick={createDocument}>Open a blank page</button>}</motion.div>}</AnimatePresence>
      </section>
    </div>
    <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}><AlertDialogContent className="border-[#d8d1c5] bg-[#fffdf8]"><AlertDialogHeader><AlertDialogTitle>Delete this document?</AlertDialogTitle><AlertDialogDescription>“{deleteTarget?.title || "Untitled document"}” and its uploaded images will be permanently removed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep document</AlertDialogCancel><AlertDialogAction onClick={() => void deleteDocument()} className="bg-[#9a4139] hover:bg-[#81352f]">Delete document</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <SettingsModal isOpen={settingsOpen} onClose={() => setSettingsOpen(false)} user={{ name: user.name, avatar: user.avatar }} />
  </main>;
}
