"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRightIcon, CheckCircleIcon, CopyIcon, DotsThreeIcon, FilePlusIcon, GearSixIcon, GlobeHemisphereWestIcon, MagnifyingGlassIcon, NotePencilIcon, SignOutIcon, SparkleIcon, TrashIcon, UsersThreeIcon } from "@phosphor-icons/react";
import { toast } from "sonner";
import { DocumentsFolderIcon, OmnidocLogo } from "@/components/omnidoc-logo";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { createClient } from "@/lib/supabase/client";
import { MobileBottomNav } from "@/components/mobile-bottom-nav";
import "./dashboard.css";

const SettingsModal = dynamic(() => import("@/components/setting-modal").then((module) => module.SettingsModal), { ssr: false });
type Person = { id: string; name: string; avatar?: string | null };
type Publication = { id: string; slug: string; isActive: boolean; publishedAt: string; updatedAt: string };
type DashboardDoc = { id: string; title: string; status: "WORKING_DRAFT" | "COMPLETE"; previewText: string; previewImageUrl: string | null; wordCount: number; updatedAt: string; lastEditedAt: string; owned: boolean; publication: Publication | null; collaborators: { role: string; user: Person }[] };
type DashboardUser = { id: string; name: string; email: string; avatar: string };
type Filter = "all" | "draft" | "complete" | "published" | "shared";
function initials(name: string) { return name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function publicationPath(doc: DashboardDoc) { return doc.publication ? `/p/${doc.publication.id}/${doc.publication.slug}` : ""; }

export default function DashboardClient({ user, documents: initialDocuments, greeting }: { user: DashboardUser; documents: DashboardDoc[]; greeting: string }) {
  const router = useRouter(); const reducedMotion = useReducedMotion();
  const [documents, setDocuments] = useState(initialDocuments); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [error, setError] = useState<string | null>(null); const [settingsOpen, setSettingsOpen] = useState(false); const [deleteTarget, setDeleteTarget] = useState<DashboardDoc | null>(null); const [brokenImages, setBrokenImages] = useState<Set<string>>(new Set()); const [creating, startCreating] = useTransition();
  const counts = useMemo(() => ({ all: documents.length, draft: documents.filter((doc) => doc.status === "WORKING_DRAFT").length, complete: documents.filter((doc) => doc.status === "COMPLETE").length, published: documents.filter((doc) => doc.publication?.isActive).length, shared: documents.filter((doc) => !doc.owned).length }), [documents]);
  const filtered = useMemo(() => documents.filter((doc) => { const matchesQuery = `${doc.title} ${doc.previewText}`.toLowerCase().includes(query.trim().toLowerCase()); const matchesFilter = filter === "all" || (filter === "draft" && doc.status === "WORKING_DRAFT") || (filter === "complete" && doc.status === "COMPLETE") || (filter === "published" && doc.publication?.isActive) || (filter === "shared" && !doc.owned); return matchesQuery && matchesFilter; }), [documents, filter, query]);
  function createDocument() { startCreating(() => router.push("/document")); }
  async function deleteDocument() { if (!deleteTarget) return; const target = deleteTarget; setDeleteTarget(null); const previous = documents; setDocuments((items) => items.filter((item) => item.id !== target.id)); const response = await fetch(`/api/documents/${target.id}`, { method: "DELETE" }); if (!response.ok) { setDocuments(previous); setError("That document could not be deleted."); toast.error("Document could not be deleted"); } else toast.success("Document deleted"); }
  async function copyPublicLink(doc: DashboardDoc) { const path = publicationPath(doc); if (!path) return; await navigator.clipboard.writeText(`${window.location.origin}${path}`); toast.success("Public link copied"); }
  async function signOut() { router.replace("/signin"); const { error: logoutError } = await createClient().auth.signOut({ scope: "local" }); if (logoutError) toast.error("Signed out locally, but session cleanup failed."); router.refresh(); }
  const filters: Array<{ id: Filter; label: string }> = [{ id: "all", label: "All" }, { id: "draft", label: "Working drafts" }, { id: "complete", label: "Complete" }, { id: "published", label: "Published" }, { id: "shared", label: "Shared" }];
  return <main className="dash-page">
    <aside className="dash-rail"><Link href="/" className="dash-mark" aria-label="Omnidoc"><OmnidocLogo priority className="dash-logo-image" /></Link><nav><button className="active" aria-label="Documents folder"><DocumentsFolderIcon className="documents-folder-icon" /></button><button onClick={() => setSettingsOpen(true)} aria-label="Settings"><GearSixIcon /></button></nav><button onClick={signOut} aria-label="Sign out"><SignOutIcon /></button></aside>
    <MobileBottomNav className="dash-mobile-nav" ariaLabel="Dashboard navigation" items={[{id:"documents",label:"Docs",icon:<DocumentsFolderIcon/>,onClick:()=>router.push("/dashboard"),active:true},{id:"new",label:"New",icon:<FilePlusIcon/>,onClick:createDocument},{id:"settings",label:"Settings",icon:<GearSixIcon/>,onClick:()=>setSettingsOpen(true)},{id:"signout",label:"Sign out",icon:<SignOutIcon/>,onClick:()=>void signOut()}]} />
    <div className="dash-content">
      <header className="dash-header"><Link href="/" className="dash-wordmark"><OmnidocLogo className="dash-wordmark-logo" />Omnidoc</Link><div className="dash-user"><span>{user.name}</span><div>{user.avatar?.startsWith("http") ? <img src={user.avatar} alt="" /> : initials(user.name)}</div></div></header>
      <section className="dash-hero"><div><span className="dash-eyebrow">Documents</span><h1>Good {greeting},<br /><i>{user.name.split(" ")[0]}.</i></h1><p>Everything in progress, ready to share, and published lives in one quiet place.</p></div><button className="dash-new" onClick={createDocument} disabled={creating}><FilePlusIcon />{creating ? "Opening…" : "New document"}<ArrowRightIcon /></button></section>
      <section className="dash-library"><div className="dash-library-head"><div><h2>Your library</h2><span>{documents.length} {documents.length === 1 ? "document" : "documents"}</span></div><label><MagnifyingGlassIcon /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles and pages" aria-label="Search documents" /></label></div><div className="dash-filters" role="tablist" aria-label="Filter documents">{filters.map((item) => <button key={item.id} role="tab" aria-selected={filter === item.id} onClick={() => setFilter(item.id)}>{item.label}<span>{counts[item.id]}</span></button>)}</div>
        {error && <div role="alert" className="dash-error">{error}<button onClick={() => setError(null)}>Dismiss</button></div>}
        <AnimatePresence mode="popLayout">{filtered.length ? <motion.div layout className="dash-grid">{filtered.map((doc, index) => <motion.article layout key={doc.id} initial={reducedMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .2, delay: reducedMotion ? 0 : Math.min(index * .025, .12) }} className="dash-doc">
          <Link href={`/document/${doc.id}`} prefetch className="dash-doc-link"><div className={`dash-page-preview ${doc.previewImageUrl && !brokenImages.has(doc.id) ? "has-image" : ""}`}>{doc.previewImageUrl && !brokenImages.has(doc.id) && <img src={doc.previewImageUrl} alt="" onError={() => setBrokenImages((items) => new Set(items).add(doc.id))} />}<div className="dash-preview-copy"><span className={`dash-status ${doc.status === "COMPLETE" ? "complete" : ""}`}>{doc.status === "COMPLETE" ? <CheckCircleIcon /> : <NotePencilIcon />}{doc.status === "COMPLETE" ? "Complete" : "Working draft"}</span><p>{doc.previewText || "A blank page, ready for the first thought."}</p></div></div><div className="dash-doc-meta"><div><h3>{doc.title || "Untitled document"}</h3><p>{doc.owned ? "Owned by you" : "Shared with you"} · {formatDate(doc.lastEditedAt)}</p></div><ArrowRightIcon /></div></Link>
          <div className="dash-doc-foot"><div className="dash-avatars">{doc.collaborators.slice(0, 3).map(({ user: person }) => <span key={person.id} title={person.name}>{initials(person.name)}</span>)}{!doc.collaborators.length && <span className="solo"><UsersThreeIcon /></span>}</div><span className="dash-word-count">{doc.wordCount.toLocaleString("en-US")} words</span>{doc.publication?.isActive && <Link href={publicationPath(doc)} className="dash-live" title="View published page"><GlobeHemisphereWestIcon />Live</Link>}<DropdownMenu><DropdownMenuTrigger asChild><button className="dash-more" aria-label={`Actions for ${doc.title}`}><DotsThreeIcon weight="bold" /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => router.push(`/document/${doc.id}`)}>Open document</DropdownMenuItem>{doc.publication?.isActive && <><DropdownMenuItem onClick={() => window.open(publicationPath(doc), "_blank", "noopener,noreferrer")}>View published page</DropdownMenuItem><DropdownMenuItem onClick={() => void copyPublicLink(doc)}><CopyIcon />Copy public link</DropdownMenuItem></>}{doc.owned && <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setDeleteTarget(doc)}><TrashIcon />Delete</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>
        </motion.article>)}</motion.div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="dash-empty"><SparkleIcon weight="duotone" /><h3>{query ? "Nothing matches that search" : filter === "all" ? "A clean page is waiting" : `No ${filters.find((item) => item.id === filter)?.label.toLowerCase()} yet`}</h3><p>{query ? "Try another title or phrase." : "Start a document and it will appear here as soon as the first thought lands."}</p>{!query && filter === "all" && <button onClick={createDocument}>Open a blank page</button>}</motion.div>}</AnimatePresence>
      </section>
    </div>
    <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}><AlertDialogContent className="border-[#d8d1c5] bg-[#fffdf8]"><AlertDialogHeader><AlertDialogTitle>Delete this document?</AlertDialogTitle><AlertDialogDescription>“{deleteTarget?.title || "Untitled document"}” and its uploaded images will be permanently removed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep document</AlertDialogCancel><AlertDialogAction onClick={() => void deleteDocument()} className="bg-[#9a4139] hover:bg-[#81352f]">Delete document</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <SettingsModal isOpen={settingsOpen} onClose={() => setSettingsOpen(false)} user={{ name: user.name, avatar: user.avatar }} />
  </main>;
}
