"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState, useTransition } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRightIcon, CheckCircleIcon, CopyIcon, DotsThreeIcon, FilesIcon, GearSixIcon, GlobeHemisphereWestIcon, ListIcon, MagnifyingGlassIcon, NotePencilIcon, SignOutIcon, SparkleIcon, TrashIcon, UsersThreeIcon } from "@phosphor-icons/react";
import { toast } from "sonner";
import { OmnidocLogo } from "@/components/omnidoc-logo";
import { GalaxyButton } from "@/components/galaxy-button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sheet, SheetContent, SheetDescription, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { createClient } from "@/lib/supabase/client";
import "./dashboard.css";

const SettingsModal = dynamic(() => import("@/components/setting-modal").then((module) => module.SettingsModal), { ssr: false });
type Person = { id: string; name: string; avatar?: string | null };
type Publication = { id: string; slug: string; isActive: boolean; publishedAt: string; updatedAt: string };
type DashboardDoc = { id: string; title: string; status: "WORKING_DRAFT" | "COMPLETE"; previewText: string; previewImageUrl: string | null; wordCount: number; updatedAt: string; lastEditedAt: string; owned: boolean; publication: Publication | null; collaborators: { role: string; user: Person }[] };
type DashboardUser = { id: string; name: string; email: string; avatar: string };
type Filter = "all" | "draft" | "complete" | "published" | "shared";
function initials(name: string) { return name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function publicationPath(doc: DashboardDoc) { return doc.publication ? `/p/${doc.publication.id}/${doc.publication.slug}` : ""; }
async function clearDocumentCache(documentId: string) {
  localStorage.removeItem(`document-${documentId}-backup`);
  if (typeof indexedDB === "undefined") return;
  await new Promise<void>((resolve) => {
    const request = indexedDB.deleteDatabase(`omnidoc:${documentId}`);
    request.onsuccess = request.onerror = request.onblocked = () => resolve();
  });
}
function uniqueDocuments(items: DashboardDoc[]) {
  const seen = new Set<string>();
  return items.filter((document) => {
    if (seen.has(document.id)) return false;
    seen.add(document.id);
    return true;
  });
}

export default function DashboardClient({ user, documents: initialDocuments, greeting }: { user: DashboardUser; documents: DashboardDoc[]; greeting: string }) {
  const router = useRouter(); const reducedMotion = useReducedMotion();
  const [documents, setDocuments] = useState(() => uniqueDocuments(initialDocuments)); const [displayName, setDisplayName] = useState(user.name); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [error, setError] = useState<string | null>(null); const [settingsOpen, setSettingsOpen] = useState(false); const [mobileMenuOpen, setMobileMenuOpen] = useState(false); const [deleteTarget, setDeleteTarget] = useState<DashboardDoc | null>(null); const [brokenImages, setBrokenImages] = useState<Set<string>>(new Set()); const [avatarFailed, setAvatarFailed] = useState(false); const [creating, startCreating] = useTransition(); const [signingOut, setSigningOut] = useState(false);
  useEffect(() => setDocuments(uniqueDocuments(initialDocuments)), [initialDocuments]);
  useEffect(() => setDisplayName(user.name), [user.name]);
  useEffect(() => setAvatarFailed(false), [user.avatar]);
  const avatarSrc = user.avatar?.startsWith("https://") && !avatarFailed ? user.avatar : null;
  const counts = useMemo(() => ({ all: documents.length, draft: documents.filter((doc) => doc.status === "WORKING_DRAFT").length, complete: documents.filter((doc) => doc.status === "COMPLETE").length, published: documents.filter((doc) => doc.publication?.isActive).length, shared: documents.filter((doc) => !doc.owned).length }), [documents]);
  const filtered = useMemo(() => documents.filter((doc) => { const matchesQuery = `${doc.title} ${doc.previewText}`.toLowerCase().includes(query.trim().toLowerCase()); const matchesFilter = filter === "all" || (filter === "draft" && doc.status === "WORKING_DRAFT") || (filter === "complete" && doc.status === "COMPLETE") || (filter === "published" && doc.publication?.isActive) || (filter === "shared" && !doc.owned); return matchesQuery && matchesFilter; }), [documents, filter, query]);
  function createDocument() { startCreating(() => router.push("/document")); }
  async function deleteDocument() { if (!deleteTarget) return; const target = deleteTarget; setDeleteTarget(null); setError(null); setDocuments((items) => items.filter((item) => item.id !== target.id)); try { const response = await fetch(`/api/documents/${target.id}`, { method: "DELETE" }); if (!response.ok) throw new Error("Delete failed"); await clearDocumentCache(target.id); toast.success("Document deleted"); } catch { setDocuments((items) => uniqueDocuments([...items, target]).sort((a, b) => Date.parse(b.lastEditedAt) - Date.parse(a.lastEditedAt))); setError("That document could not be deleted."); toast.error("Document could not be deleted"); } }
  async function copyPublicLink(doc: DashboardDoc) { const path = publicationPath(doc); if (!path) return; try { await navigator.clipboard.writeText(`${window.location.origin}${path}`); toast.success("Public link copied"); } catch { toast.error("Could not copy the public link"); } }
  async function signOut() { if (signingOut) return; setSigningOut(true); try { const { error: logoutError } = await createClient().auth.signOut({ scope: "local" }); if (logoutError) throw logoutError; router.replace("/signin"); router.refresh(); } catch { toast.error("Could not sign out. Please try again."); setSigningOut(false); } }
  const filters: Array<{ id: Filter; label: string }> = [{ id: "all", label: "All" }, { id: "draft", label: "Working drafts" }, { id: "complete", label: "Complete" }, { id: "published", label: "Published" }, { id: "shared", label: "Shared" }];
  return <main className="dash-page">
    <aside className="dash-rail" aria-label="Workspace navigation"><Link href="/dashboard" className="dash-mark" aria-label="Omnidoc dashboard"><OmnidocLogo priority className="dash-logo-image" /><span>omnidoc<span className="dash-brand-dot">.</span></span></Link><div className="dash-rail-section">Workspace</div><nav aria-label="Main navigation"><Link href="/dashboard" className="dash-nav-link active" aria-current="page"><FilesIcon /><span>Documents</span></Link><button className="dash-nav-link" onClick={() => setSettingsOpen(true)}><GearSixIcon /><span>Settings</span></button></nav><div className="dash-rail-bottom"><div className="dash-rail-profile"><span className="dash-rail-avatar">{avatarSrc ? <img src={avatarSrc} alt="" onError={() => setAvatarFailed(true)} /> : initials(displayName)}</span><span className="dash-rail-identity"><strong>{displayName}</strong><small>{user.email}</small></span></div><button className="dash-nav-link dash-signout" onClick={() => void signOut()} disabled={signingOut}><SignOutIcon /><span>{signingOut ? "Signing out…" : "Sign out"}</span></button></div></aside>
    <div className="dash-content">
      <header className="dash-header"><div className="dash-header-start"><Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}><SheetTrigger asChild><button className="dash-mobile-menu" aria-label="Open workspace menu"><ListIcon weight="bold" /></button></SheetTrigger><SheetContent side="left" className="dash-mobile-sheet"><SheetTitle className="sr-only">Workspace menu</SheetTitle><SheetDescription className="sr-only">Navigate your workspace and manage your account.</SheetDescription><Link href="/dashboard" className="dash-mark" onClick={() => setMobileMenuOpen(false)}><OmnidocLogo priority className="dash-logo-image" /><span>omnidoc<span className="dash-brand-dot">.</span></span></Link><div className="dash-rail-section">Workspace</div><nav aria-label="Mobile workspace navigation"><Link href="/dashboard" className="dash-nav-link active" aria-current="page" onClick={() => setMobileMenuOpen(false)}><FilesIcon /><span>Documents</span></Link><button className="dash-nav-link" onClick={() => { setMobileMenuOpen(false); setSettingsOpen(true); }}><GearSixIcon /><span>Settings</span></button></nav><div className="dash-rail-bottom"><div className="dash-rail-profile"><span className="dash-rail-avatar">{avatarSrc ? <img src={avatarSrc} alt="" onError={() => setAvatarFailed(true)} /> : initials(displayName)}</span><span className="dash-rail-identity"><strong>{displayName}</strong><small>{user.email}</small></span></div><button className="dash-nav-link dash-signout" onClick={() => void signOut()} disabled={signingOut}><SignOutIcon /><span>{signingOut ? "Signing out…" : "Sign out"}</span></button></div></SheetContent></Sheet><span className="dash-header-label">Workspace <span>/</span> Documents</span></div><div className="dash-user"><span>{displayName}</span><div>{avatarSrc ? <img src={avatarSrc} alt="" onError={() => setAvatarFailed(true)} /> : initials(displayName)}</div></div></header>
      <section className="dash-hero"><div><span className="dash-eyebrow">Documents</span><h1>Good {greeting},<br /><i>{displayName.split(" ")[0]}.</i></h1><p>Everything in progress, ready to share, and published lives in one quiet place.</p></div><GalaxyButton label={creating ? "Opening…" : "New document"} onClick={createDocument} disabled={creating} aria-busy={creating} /></section>
      <section className="dash-library"><div className="dash-library-head"><div><h2>Your library</h2><span>{documents.length} {documents.length === 1 ? "document" : "documents"}</span></div><label><MagnifyingGlassIcon /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles and pages" aria-label="Search documents" /></label></div><div className="dash-filters" role="group" aria-label="Filter documents">{filters.map((item) => <button key={item.id} aria-pressed={filter === item.id} onClick={() => setFilter(item.id)}>{item.label}<span>{counts[item.id]}</span></button>)}</div>
        {error && <div role="alert" className="dash-error">{error}<button onClick={() => setError(null)}>Dismiss</button></div>}
        <AnimatePresence mode="popLayout">{filtered.length ? <motion.div layout className="dash-grid">{filtered.map((doc, index) => <motion.article layout key={doc.id} initial={reducedMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .2, delay: reducedMotion ? 0 : Math.min(index * .025, .12) }} className="dash-doc">
          <Link href={`/document/${doc.id}`} prefetch className="dash-doc-link"><div className={`dash-page-preview ${doc.previewImageUrl && !brokenImages.has(doc.id) ? "has-image" : ""}`}>{doc.previewImageUrl && !brokenImages.has(doc.id) && <img src={doc.previewImageUrl} alt="" onError={() => setBrokenImages((items) => new Set(items).add(doc.id))} />}<div className="dash-preview-copy"><span className={`dash-status ${doc.status === "COMPLETE" ? "complete" : ""}`}>{doc.status === "COMPLETE" ? <CheckCircleIcon /> : <NotePencilIcon />}{doc.status === "COMPLETE" ? "Complete" : "Working draft"}</span><p>{doc.previewText || "A blank page, ready for the first thought."}</p></div></div><div className="dash-doc-meta"><div><h3>{doc.title || "Untitled document"}</h3><p>{doc.owned ? "Owned by you" : "Shared with you"} · {formatDate(doc.lastEditedAt)}</p></div><ArrowRightIcon /></div></Link>
          <div className="dash-doc-foot"><div className="dash-avatars">{doc.collaborators.slice(0, 3).map(({ user: person }) => <span key={person.id} title={person.name}>{initials(person.name)}</span>)}{!doc.collaborators.length && <span className="solo"><UsersThreeIcon /></span>}</div><span className="dash-word-count">{doc.wordCount.toLocaleString("en-US")} words</span>{doc.publication?.isActive && <Link href={publicationPath(doc)} className="dash-live" title="View published page"><GlobeHemisphereWestIcon />Live</Link>}<DropdownMenu><DropdownMenuTrigger asChild><button className="dash-more" aria-label={`Actions for ${doc.title}`}><DotsThreeIcon weight="bold" /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => router.push(`/document/${doc.id}`)}>Open document</DropdownMenuItem>{doc.publication?.isActive && <><DropdownMenuItem onClick={() => window.open(publicationPath(doc), "_blank", "noopener,noreferrer")}>View published page</DropdownMenuItem><DropdownMenuItem onClick={() => void copyPublicLink(doc)}><CopyIcon />Copy public link</DropdownMenuItem></>}{doc.owned && <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setDeleteTarget(doc)}><TrashIcon />Delete</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>
        </motion.article>)}</motion.div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="dash-empty"><SparkleIcon weight="duotone" /><h3>{query ? "Nothing matches that search" : filter === "all" ? "A clean page is waiting" : `No ${filters.find((item) => item.id === filter)?.label.toLowerCase()} yet`}</h3><p>{query ? "Try another title or phrase." : "Start a document and it will appear here as soon as the first thought lands."}</p>{!query && filter === "all" && <button onClick={createDocument}>Open a blank page</button>}</motion.div>}</AnimatePresence>
      </section>
    </div>
    <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}><AlertDialogContent className="border-[#d8d1c5] bg-[#fffdf8]"><AlertDialogHeader><AlertDialogTitle>Delete this document?</AlertDialogTitle><AlertDialogDescription>“{deleteTarget?.title || "Untitled document"}” and its uploaded images will be permanently removed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep document</AlertDialogCancel><AlertDialogAction onClick={() => void deleteDocument()} className="bg-[#9a4139] hover:bg-[#81352f]">Delete document</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <SettingsModal isOpen={settingsOpen} onClose={() => setSettingsOpen(false)} onProfileSaved={setDisplayName} user={{ name: displayName, avatar: user.avatar }} />
  </main>;
}
